APP_NAME = "pNJU"
WEBSITE = "http://pnju.dayanjia.com"
PREFERENCE_FILENAME = 'preference'
SESSION_FILENAME = 'session'
URL = "http://p.nju.edu.cn/portal.do"
IMG_URL = "http://p.nju.edu.cn/portal/img.html"
USER_AGENT = "Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; WOW64; Trident/6.0)"
#SESSION_ID = "imdevelopedbyclippitakazlt"
LOGIN_STATS_URL = "http://pnjuservice.dayanjia.com/1/login/"
CHECK_VERSION_URL = "http://pnjuservice.dayanjia.com/version.txt"
BRAS_LOGIN_URL = "http://bras.nju.edu.cn/selfservice/auth.html"
BRAS_URL = "http://bras.nju.edu.cn/selfservice/"
CONNECTION_TIMEOUT = 30
